apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-git-lab-proxy-config
data:
  default.conf: |
    server {
      listen 80;

      location / {
        proxy_pass http://vm-git-lab-app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }

      location /health {
        proxy_pass http://vm-git-lab-app:8080/health;
      }
    }
